[package]
name = "raft-validation"
version = "0.1.0"
edition = "2021"

[dependencies]
raft-core = { path = "../core" }
raft-test-utils = { path = "../test-utils" }
indexmap.workspace = true
rand.workspace = true
serde_json.workspace = true

[dev-dependencies]


